lsi: false
safe: true
source: [https://raw.githubusercontent.com/ralseiplushie/ralseiplushie/main/README.md]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
